### ISSUE TITLE
Explore disabling name field for OpenAddresses Records

### ISSUE THREAD

**Issue by riordan** [pelias/openaddresses#25] opened 2016-01-06 15:58 UTC
Investigate #24
- [ ] Disable NAME for OpenAddresses
- [ ] Disable NAME for OSM records with only address fields

**Comment by orangejulius** [comment] 2019-03-05 21:22
Duplicate of https://github.com/pelias/pelias/issues/168

**Closed by orangejulius** 2019-03-05 21:22 UTC
Labels: addresses, processed
