### ISSUE TITLE
Allow street-less records in white-listed countries

### ISSUE THREAD

**Issue by trescube** [pelias/openaddresses#218] opened 2017-01-24 18:53 UTC
Some countries allow addresses without streets.  So far, it just appears to be the Czech Republic.  Here are two examples:

* č.p. 360, 79862 Rozstání
* č.ev. 9, 79857 Rakůvka

These can be parsed as: 
```
{
  housenumber: 'č.p. 360',
  postcode: '79862',
  city: 'Rozstání'
}
```

and:
```
{
  housenumber: 'č.ev. 9',
  postcode: '79857',
  city: 'Rakůvka'
}
```

**Comment by orangejulius** [comment] 2018-11-03 02:06
Duplicate of https://github.com/pelias/pelias/issues/642

**Closed by orangejulius** 2018-11-03 02:06 UTC
Labels: processed
