### ISSUE TITLE
Addresses without street not get imported into Pelias

### ISSUE THREAD

**Issue by macieg** [pelias/openaddresses#462] opened 2020-04-19 15:38 UTC
**Describe the bug**
According to this file:
https://github.com/pelias/openaddresses/blob/master/lib/isValidCsvRecord.js
_Street_ is a required property for an address record to be valid.

It's not true for countries like Poland or Czech Republic, where you can find many small villages without street names.

It causes such addresses not to be included into the elasticsearch index. I propose to remove this parameter as required. I'm happy to contribute.

**Steps to Reproduce**
Follow the steps from here - https://github.com/pelias/docker

**Expected behavior**
Pelias shouldn't ignore addresses without street names.

**Environment (please complete the following information):**
Mac OSX 10.15.3

**Comment by missinglink** [comment] 2020-04-19 16:10
Duplicate of https://github.com/pelias/pelias/issues/642

See: https://github.com/pelias/pelias/issues/642#issuecomment-433866009

Please add any additional information to that ticket so we can track it all in one place.

**Closed by missinglink** 2020-04-19 16:10 UTC
Labels: bug

**Comment by orangejulius** [comment] 2020-04-19 16:28
@macieg thanks for mentioning this. As Peter mentioned we did indeed know about this and would love to fix it :)

One OA-specific piece of information I'd love to have is some example files where there are addresses without streets.

As discussed in the linked issue, we're a little concerned that allowing addresses without a street would import a lot of invalid records across the planet. Having some known good examples would help us judge the impact. Thanks!
